server:
  port: 8080
  error:
    whitelabel:
      enabled: false
spring:
  data:
    rest:
      basePath: /api
  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: true
    hibernate:
      ddlAuto: update
  jackson:
    property_naming_strategy: SNAKE_CASE
    serialization:
      fail_on_empty_beans: false

logging:
  level:
    root: ERROR
    org:
      springframework:
        security: DEBUG
        web: DEBUG

security:
  basic:
    enabled: false
  oauth2:
    resource:
      filter-order: 3
  jwt:
    enabled: true
  role_hierarchy:
    ROLE_SUPERUSER: [ ROLE_ADMIN ]
    ROLE_ADMIN: [ ROLE_USER ]
    ROLE_USER: [ ROLE_ANON ]

management:
  security:
    enabled: true
